# Generated by Django 5.0.6 on 2024-07-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bankaccount_monies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
