# Generated by Django 5.0.6 on 2024-07-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_bankaccount_ifsc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='contact_number',
        ),
    ]
