# Generated by Django 5.0.6 on 2024-07-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_bankaccount_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='monies',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='branch_address',
            new_name='bank_address',
        ),
    ]
