# Generated by Django 5.0.6 on 2024-07-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_monies_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='identity_verified',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='picture',
        ),
    ]
